travis:
  secure:
    BINSTAR_TOKEN: AHcRJz6DN19SnMek7i+5zkBmna5zae3xwMTl5VmoKhlDBqBa5loAcbtxIgrru/AmYzXtNpsczjGUOUkil8iJDUahsDtdREsAENiTJx35+H1howRJaGt/9eoXy/FJZe48oGowHMnnJP6lft6xOGzQ/SYHBi/NErZf66Q340c4CfAhoWGAKCU8qtokIo8mdjNePCClwHA2cTk9HU+CIuY4+X4mt8JhWSh6lTp2pbzwbnLeDMqNoH0ZJLNFNk+dS6AlWyeEKxOaLcMfR9TDqanE8K/Iem0chQYJkGzWcnCVN0eJCCfQGd3cHa5hAOgo0Eqisp8cnTi8SUHjXBz8nGanIpTjs/ZKlkWy/7l6VlamB74mKXhQno/dU+5qKuhrieq12JMYRcLKQMWsDEfZIaZFOvkMNF7j05yRtfOMiWDKSonZAmeGwTyrXb11LxCUu8ciPC6j1Q49RtD1FUWipZfbY3POVtdzvLVvM8cvHXzcAUwiItzAyniu78NQtiu2i+zITgIcGQhb25bucY0glVYs8v1eiP4UAMYeUr4ySBBBtU/iDr5PlWwbGK+wL5lrR0c8CoiUuszndSCiw0f31oUglsxXNsShi1gK7qK/N+dpwnYTk0P8ekjqKDehy4IDXlQ9wRpe1OUe0NLDQA0eGPuVsfogEs2Z9HF/8K7MjcaLSFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
